import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

import { useAppSelector, useAppDispatch } from "#app/hook";
import { changeTheme } from "#app/features/themeSlice";
import StandartLO from "#layout/ThemeLayout";

const Home: NextPage = () => {
  const theme = useAppSelector((state) => state.theme.theme);
  const dispatch = useAppDispatch();

  return (
    <StandartLO>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <button onClick={() => dispatch(changeTheme({ theme: "change" }))}>
          {theme}
        </button>
      </Container>
    </StandartLO>
  );
};

export default Home;

const Container = styled.div`
  background-color: ${(props) => props.theme.color.white};
  color: ${(props) => props.theme.color.textPrimary};
`;
