import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useAppSelector, useAppDispatch } from "@app/hook";

import { changeTheme } from "@app/features/themeSlice";

const Home: NextPage = () => {
  const theme = useAppSelector((state) => state.theme.theme);
  const dispatch = useAppDispatch();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Personal Website II</h1>
      <p>Theme: {theme}</p>
      <button onClick={() => dispatch(changeTheme({ theme: "change" }))}>
        Change Theme
      </button>
    </div>
  );
};

export default Home;
